### ISSUE TITLE
LDDiffuse.forward() missing 1 argument

### ISSUE THREAD

**Issue by hello-wwy** [Zhangyong-Tang/GMMT-AAAI2024#2]
Hello, the forward method of the LDDiffuse class you provided requires four parameters: (fused_fea, A, fea_rgb, fea_tir), but only three parameters are passed in actual use, that is, self.lddiffuse(opt_feat, token2feature(enc_opt1), token2feature(enc_opt2)). Is there an error? looking forward to your answer.

**Comment by Zhangyong-Tang** [comment]
Hi, many thanks for your attention.
Following your questions, I have checked my code and found that this 'A' is actually not appeared in the code.
It should be a mistake introduced when preparing for publication.
Thanks again for pointing out this mistake.

**Comment by hello-wwy** [comment]
> Hi, many thanks for your attention. Following your questions, I have checked my code and found that this 'A' is actually not appeared in the code. It should be a mistake introduced when preparing for publication. Thanks again for pointing out this mistake.

Thank you for your response. Another question is, does LDDiffuse use the default settings of Total=1000 and Sample=5 during initialization, as it seems you haven't provided a configuration file.

**Comment by Zhangyong-Tang** [comment]
Total=1000, and Samle step=1.
About the step in the backward process, it's discussed in the paper or the supplementary. Hopefully you can find what you want.😄
