### ISSUE TITLE
model parameters initialized

### ISSUE THREAD

**Issue by LiShenglana** [Zhangyong-Tang/GMMT-AAAI2024#3]
Hello, how are the model parameters used in lddiffuse initialized and are the pre-trained models loaded? Thank you!

**Comment by Zhangyong-Tang** [comment]
Hi, thanks for your attention.
The parameters for lddiffuse are trained from scratch, so this part is embedded in the final model.
Based on this, we just use the torch.load to load the model.
More details can be found in the supplementary materials.

**Comment by LiShenglana** [comment]
> Hi, thanks for your attention. The parameters for lddiffuse are trained from scratch, so this part is embedded in the final model. Based on this, we just use the torch.load to load the model. More details can be found in the supplementary materials.

Thanks for your reply. That hepls alot.
